#!/bin/bash
outfile=`ls -t *.out | head -n 1 | awk -F\. '{print $1;}'` # latest out file name
runfile="run.qsub" # script file name

if test -e $outfile.out; then # out file exists
 # qsub script
 echo "#PBS -N `pwd | sed -e 's/\(.*\)home\/\(.*\)/\\2/g' | sed -e 's/\//_/g' `" > $runfile
 echo "#PBS -l walltime=0:10:00">> $runfile
 echo "#PBS -l select=1:ncpus=12:mem=1gb:scratch_local=10gb:cluster=tyra">> $runfile
 echo "#PBS -j oe">> $runfile
 echo >> $runfile
 echo "cat \$PBS_NODEFILE">>$runfile
 echo "echo \"Hostname \" \`hostname\`" >> $runfile
 echo "echo \"PBS_NODEFILE \$PBS_NODEFILE\"">> $runfile

 echo "SOURCE=`pwd`" >>$runfile
 echo "echo SOURCE= \$SOURCE " >>$runfile
 echo "echo script sub4" >> $runfile
 echo "echo \"Hostname \" \`hostname\` >>\$SOURCE/machine.txt" >> $runfile
 
 echo "cd \$SOURCE" >> $runfile
 echo "module add intelmpi-5.0.1" >> $runfile
 echo "export OMP_NUM_THREADS=12" >> $runfile
 echo "./out/oa1.out < input.txt > output1.txt" >> $runfile
 echo "./out/oa2.out < input.txt > output2.txt" >> $runfile
 echo "./out/oa3.out < input.txt > output3.txt" >> $runfile
 echo "./out/oa4.out < input.txt > output4.txt" >> $runfile
 echo "./out/oa5.out < input.txt > output5.txt" >> $runfile
 echo "./out/oa6.out < input.txt > output6.txt" >> $runfile
 echo "./out/oa7.out < input.txt > output7.txt" >> $runfile
 echo "./out/oa8.out < input.txt > output8.txt" >> $runfile
 echo "./out/oa9.out < input.txt > output9.txt" >> $runfile
 echo "./out/oa10.out < input.txt > output10.txt" >> $runfile
 echo "./out/oa11.out < input.txt > output11.txt" >> $runfile
 echo "./out/oa12.out < input.txt > output12.txt" >> $runfile
 echo "./out/oa13.out < input.txt > output13.txt" >> $runfile
 echo "./out/oa121.out < input.txt > output121.txt" >> $runfile
 echo "./out/oa122.out < input.txt > output122.txt" >> $runfile
 echo "./out/oa123.out < input.txt > output123.txt" >> $runfile
 echo "./out/oa124.out < input.txt > output124.txt" >> $runfile
 echo "./out/oa125.out < input.txt > output125.txt" >> $runfile
 echo "./out/oa126.out < input.txt > output126.txt" >> $runfile
 echo "./out/oa127.out < input.txt > output127.txt" >> $runfile
 echo "./out/oa128.out < input.txt > output128.txt" >> $runfile
 echo "./out/oa129.out < input.txt > output129.txt" >> $runfile
 echo "./out/oa1210.out < input.txt > output1210.txt" >> $runfile
 echo "./out/oa1211.out < input.txt > output1211.txt" >> $runfile
 echo "./out/oa1212.out < input.txt > output1212.txt" >> $runfile
 echo "./out/oa1213.out < input.txt > output1213.txt" >> $runfile
 echo "./out/oa21.out < input.txt > output21.txt" >> $runfile
 echo "./out/oa22.out < input.txt > output22.txt" >> $runfile
 echo "./out/oa23.out < input.txt > output23.txt" >> $runfile
 echo $runfile "created"
else
 echo "There are no out files!"
fi


