#!/bin/bash
outfile=`ls -t *.out | head -n 1 | awk -F\. '{print $1;}'` # latest out file name
runfile="run.qsub" # script file name

if test -e $outfile.out; then # out file exists
 # qsub script
 echo "#PBS -N `pwd | sed -e 's/\(.*\)home\/\(.*\)/\\2/g' | sed -e 's/\//_/g' `" > $runfile
 echo "#PBS -l walltime=0:10:00">> $runfile
 echo "#PBS -l select=1:ncpus=4:mem=1gb:scratch_local=10gb">> $runfile
 echo "#PBS -j oe">> $runfile
 echo >> $runfile
 echo "cat \$PBS_NODEFILE">>$runfile
 echo "echo \"Hostname \" \`hostname\`" >> $runfile
 echo "echo \"PBS_NODEFILE \$PBS_NODEFILE\"">> $runfile

 echo "SOURCE=`pwd`" >>$runfile
 echo "echo SOURCE= \$SOURCE " >>$runfile
 echo "echo script sub4" >> $runfile
 echo "echo \"Hostname \" \`hostname\` >>\$SOURCE/machine.txt" >> $runfile
 
 echo "cd \$SOURCE" >> $runfile
 echo "module add intelmpi-5.0.1" >> $runfile
 echo "mpirun -n 4 ./a.out <input.txt" >> $runfile
 echo $runfile "created"
else
 echo "There are no out files!"
fi


